GET {host}/api/v1/invoices
Accept: application/json

###
GET {host}/api/v1/invoices
Accept: application/json


###
POST {{host}}/api/v1/invoices/{{id}}/approve
Accept: application/json
Content-Type: application/json

